### PR TITLE
Fix queries marshalling

### LINKED ISSUE #284: Be1: meeting/create response does not respect the JSON-RPC protocol
submitting this JSON-RPC request

```
{
   "id":3,
   "method":"publish",
   "params":{
      "channel":"/root/InXJxwoGiUC1wWjmq0MYXFFg0SvErmH0aNtoCu88OF0=",
      "message":{
         "data":"eyJvYmplY3QiOiJtZWV0aW5nIiwiYWN0aW9uIjoiY3JlYXRlIi…1VDRlWGM3VVVhSHJNaDVaMm1sZWJSYmJ6ZlI0Uk9ZTnc9In0=",
         "message_id":"XVr8I/iusOEJ424frFFmJddSB43kAp6fr1zo1XFMcKo=",
         "sender":"S7+QrjH8suZZXAFhAwhiXnpgX6DD+DhNuLjnkNDYolc=",
         "signature":"nCApA1hQaya1WWCeIxLru+XiprMUvual580DUk4AyWVXz4/arAQj8xy8oNcEzjRinN5Hd+e1ByM4BWYgQ+NqDA==",
         "witness_signatures":[]
      }
   }
}
```

I got this in response:

```
{
   "jsonrpc":"2.0",
   "Subscribe":null,
   "Unsubscribe":null,
   "Publish":null,
   "Catchup":null,
   "Broadcast":{
      "method":"broadcast",
      "params":{
         "channel":"/root/InXJxwoGiUC1wWjmq0MYXFFg0SvErmH0aNtoCu88OF0=",
         "message":{
            "message_id":"XVr8I/iusOEJ424frFFmJddSB43kAp6fr1zo1XFMcKo=",
            "data":"eyJvYmplY3QiOiJtZWV0aW5nIiwiYWN0aW9uIjoiY3JlYXRlIiwibmFtZSI6IkFBYWFhYSIsImNyZWF0aW9uIjoxNjE2Nzk2MTMyLCJzdGFydCI6MTYxNzMxMDkyNiwiZW5kIjoxNjE3MzEwOTI2LCJpZCI6IkxIVFBjc0dKUEh1VDRlWGM3VVVhSHJNaDVaMm1sZWJSYmJ6ZlI0Uk9ZTnc9In0=",
            "sender":"S7+QrjH8suZZXAFhAwhiXnpgX6DD+DhNuLjnkNDYolc=",
            "signature":"nCApA1hQaya1WWCeIxLru+XiprMUvual580DUk4AyWVXz4/arAQj8xy8oNcEzjRinN5Hd+e1ByM4BWYgQ+NqDA==",
            "witness_signatures":[
               
            ]
         }
      }
   }
}
```

This clearly doesn't respect the JSON-RPC protocol.

### PR DESCRIPTION
**Pull request by flmichel**
Fixes #284

### CODE REVIEW

File: be1-go/message/query.go [hunk 1]
```diff
@@ -173,24 +173,47 @@ func (q *Query) GetID() int {
...
+	case q.Publish != nil:
+		return q.Publish.Params, true
+	case q.Catchup != nil:
+		return q.Catchup.Params, true
+	}
+	return Params{}, false
+}
+
 // MarshalJSON implements custom marshaling logic for a query.
 func (q Query) MarshalJSON() ([]byte, error) {
```
Comment (pierluca) [inline be1-go/message/query.go:194]: this looks much better 👍

File: be1-go/message/query_test.go [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+		return false, nil
+	}
+	if m1 != "broadcast" {
+		if q1.GetID() != q2.GetID() {
+			return false, nil
+		}
+	}
+	if m1 == "subscribe" || m1 == "unsubscribe" {
+		return true, nil
+	}
```
Comment (pierluca) [inline be1-go/message/query_test.go:47]: you could do a switch here on m1 , dealing with broadcast, subscribe, unsubscribe and the default case. 
it might be a tiny bit more readable.

File: be1-go/message/query_test.go [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+	p1, ok := q1.GetParams()
+	if !ok {
+		return false, xerrors.Errorf("failed to get the params of the first query")
+	}
+	p2, ok := q2.GetParams()
+	if !ok {
+		return false, xerrors.Errorf("failed to get the params of the second query")
+	}
+
+	return compareMessage(*p1.Message, *p2.Message), nil
```
Comment (pierluca) [inline be1-go/message/query_test.go:57]: I'd consider grouping these 3 checks as a `compareParams` :)

File: be1-go/message/query_test.go [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+	if q1.GetChannel() != q2.GetChannel() {
+		return false, nil
+	}
+	if m1 != "broadcast" {
+		if q1.GetID() != q2.GetID() {
+			return false, nil
+		}
+	}
+	if m1 == "subscribe" || m1 == "unsubscribe" {
+		return true, nil
```
Comment (pierluca) [inline be1-go/message/query_test.go:46]: why not verifying the params (channel) here?

File: be1-go/message/query_test.go [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+	if !ok {
+		return false, xerrors.Errorf("failed to get the params of the second query")
+	}
+
+	return compareMessage(*p1.Message, *p2.Message), nil
+
+}
+
+func compareMessage(m1, m2 Message) bool {
+	return bytes.Equal(m1.MessageID, m2.MessageID) && bytes.Equal(m1.Sender, m2.Sender) && bytes.Equal(m1.Signature, m2.Signature)
```
Comment (pierluca) [inline be1-go/message/query_test.go:62]: I guess the double check doesn't hurt, though in theory MessageID already encompasses the Signature :)

File: be1-go/message/query_test.go [hunk 6]
```diff
@@ -0,0 +1,158 @@
...
+	err = json.Unmarshal(buf, genericMsg)
+	require.NoError(t, err)
+
+	q2 := *genericMsg.Query
+	res, err := compareQuery(q1, q2)
+	require.NoError(t, err)
+	require.True(t, res)
+}
+
+func Test_MarshalUnsubscribe(t *testing.T) {
```
Comment (pierluca) [inline be1-go/message/query_test.go:137]: if you're trying to be exhaustive, you might also want to check the "Catchup" message :)

**Review by pierluca — APPROVED** [review]
Minor remarks, feel free to incorporate them, but it's already pretty good !

File: be1-go/message/query.go (hunk 1 above)
Comment (flmichel) [reply be1-go/message/query.go:194]: Thank you for your review :)

File: be1-go/message/query_test.go (hunk 4 above)
Comment (flmichel) [reply be1-go/message/query_test.go:46]: I believe it is already verified earlier with the `GetChannel()` method.

File: be1-go/message/query_test.go [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+		Data:              data,
+		Sender:            []byte{byte(i)},
+		Signature:         []byte{byte(i)},
+		WitnessSignatures: []PublicKeySignaturePair{},
+	}
+
+	return msg, nil
+}
+
+func compareQueries(q1, q2 Query) (bool, error) {
```
Comment (gnarula) [inline be1-go/message/query_test.go:32]: I reckon a `(bool, error)` return time can be replaced by an `error` return type where a nil error implies true. You can even have a package level error variable for messages not being equal if you wish to check for that error at some other place

**Review by gnarula — CHANGES_REQUESTED** [review]
Looks good, just have a small suggestion regarding the return type of one of the methods

File: be1-go/message/query_test.go (hunk 7 above)
Comment (flmichel) [reply be1-go/message/query_test.go]: I remaned the method and passed the `testing.T` object. I hope it is better now

**Review by pierluca — APPROVED** [review]
LGTM !

**Review by gnarula — APPROVED** [review]
LGTM
